apiVersion: v1
kind: Service
metadata:
  name: tempo-otlp
  namespace: observability
  labels:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: otlp
    app.kubernetes.io/part-of: deploy-lgtm
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: tempo
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP
