mimir:
  structuredConfig:
    multitenancy_enabled: false
    common:
      storage:
        backend: filesystem
        filesystem:
          dir: /data
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /data/blocks
      bucket_store:
        sync_dir: /data/tsdb-sync
    ingest_storage:
      enabled: false
    ruler_storage:
      backend: filesystem
      filesystem:
        dir: /data/ruler
    alertmanager_storage:
      backend: filesystem
      filesystem:
        dir: /data/alertmanager

global:
  extraEnv:
    - name: GOMEMLIMIT
      value: 384MiB

alertmanager:
  enabled: false
ruler:
  enabled: false
kafka:
  enabled: false
minio:
  enabled: false
gateway:
  enabled: true

ingester:
  replicas: 1
  zoneAwareReplication:
    enabled: false
querier:
  replicas: 1
query_frontend:
  replicas: 1
distributor:
  replicas: 1
store_gateway:
  replicas: 1
  zoneAwareReplication:
    enabled: false
compactor:
  replicas: 1

nginx:
  enabled: false
