apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: default
  source:
    repoURL: https://github.com/Techapple78/Deploy_LGTM.git
    targetRevision: main
    path: platform/lgtm/infra-monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
