apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-network-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/Techapple78/Deploy_LGTM.git
    targetRevision: main
    path: platform/security/network-policies
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
