apiVersion: v2
name: kyverno-crds
version: 3.8.1
description: Local Kyverno CRDs wrapper for ArgoCD Server-Side Apply.
type: application
dependencies:
  - name: crds
    version: 3.8.1
    repository: file://charts/crds
  - name: kyverno-api
    version: 0.0.1-alpha.2
    repository: file://charts/kyverno-api