apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-internal-images
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: verify-internal-images
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - observability
      verifyImages:
        - imageReferences:
            - "ghcr.io/techapple78/*"
          attestors:
            - entries:
                - keyless:
                    issuer: https://token.actions.githubusercontent.com
                    subject: "https://github.com/Techapple78/Deploy_LGTM/.github/workflows/*"
