---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: observability
spec:
  encryptedData:
    admin-password: AgAuazXaAAUfM1BcF2KyEApOrgfiGCTj3+UWTKXzEiT0vVmI94JmRVLTGWllIeMOZaoQfrFMk9iURAYHKVGF4Oy03tGLQi5DRefIIytc64P1KXayu5p2FzEMiiQEoJ1ZSJq8ESXUEZaCTIDQx22NrUSw8adXRFp0LJGH0HBWLH7EgVurRkjamTu+/5bOu9r5MurBKVy9gF1QTWc9wGp4W3/plgyG5sk+QO02BTUweMBNdckhJpZ1no1kz0Q/zpc0Kf2+a5Q/O8N+o5bCu4zvgaCayx2p1dR6FUr0VR3rtSD9aHOkzLf22LYDwvqcliE4pRu//DqQtQHLZMBgW3BexgVyi05rNW3+9yrHTuZJpApGGeYks7ADqiskzLutZtdWWhWJz1ixAd5EKeSfyjmTooSHh7FS36Nj6Dc/WmRBM8nugZJMhaECNteJsl7UD9WC7+pCuG1WO7HXc4r48k/htk0BN1vscAjH5m0MjfLIwj54175EI5KutUiHZYf0jKgheY9AWT/Zu+x+TE5eHtJHrNCV6VI0IWHD6zz4FprYdIPSJxTa/gyorpmRsxYNdf270bxbA8Vp736PeWM2bezdFxwwCex7wj+oSRleTBCXQq042N5TW0mkcOdmRMcelsnaQgJccSRRHxhoXFtLUMqeBbWrSpykGmesKZKVOABDuFqYWknKwdO1tcY0M8gIcnCioeGHQtSlcJdGgSkRYCS4EZiK3ANYVYqgrPYaRsUaVrTVrA==
    admin-user: AgAbq1sT7tbq97Ccx1h+fE+gJOjdqQdrE0uUfvNZEbZxIH22BG1hTdGVAgaHj9xbJ5SSOdfFLSw/GLx90SaJVs8jbWWG0OmW5JZppdLdmNMbO/c6RTsGhNEJRT2mTtr7bn7wTGBC+KBydDblndQitgxurf4Cbt0qZyDcmeV8v3TIi9K4mC4O8I1iywlx+L+ZCD8qBo+nzYsLQD+rBZFVMnIezYdCzCG0iOW92YDl0nzkwgWE22p3k3O2m8hxRFsnf6gdqNJ6GC+gmEEfs+uaTH2zDogYzIfm3pREMfMfuMwgacGbycMl9a31oCN5XBOPU7deufFjVJpvp4kBo1oCGK1fc+1+xEUc/zavW4NPm6hajgVZ6yUfd64BDd/9WSxcPrxpY4YqtrLiY43BPo5kSWoZDgqD0YbS6yh4wKEBDG4h0SljWaZ982ipSQpmbTv9VfBfrTPLQHt4OzVsEG4vHenFQkvjYP6dTuUi21PV/nibssMBdsvl9pIDUVReftAe4zYBVLTZRZnePDJ6Q0xRf0s5ukq22VVdURftTR0+jWcyjksLqqC/nHdju56L0GFOidDiOGVqsURXWvYoAVTgUXxqOGndLrQKG6ztAjz5fPKZEXzq6+pffzvTDvEy5ltAUSxMUu4zlJ96hC7srVSLFZjPV2tasm3o/Sk6Nl6SXj/nZLhschLyWdDAIrS8BFToH+BfU8hz+w==
  template:
    metadata:
      name: grafana-admin
      namespace: observability
